#168781798 setup dotenv
andela/eagle-bn-backend pull request #15
Opened 2019-10-02 15:31 UTC by Crispy-lang

#### What does this PR do?
          Updated dotenv packages to ^8.1.0 from 6.0.0
#### How should this be manually tested?       

- import dotenv
- load all the environment variable using `dotenv.config()` from .env file
- call an environment variables using  `process.env.env_name`
#### What are the relevant pivotal tracker stories?
           #168781798

2019-10-02 15:35 UTC, urbanishimwe approved these changes

2019-10-02 17:08 UTC, swaibat approved these changes

2019-10-02 17:50 UTC, alexismajya approved these changes

2019-10-02 18:35 UTC, alexismajya requested changes
Please, Christian! could you specify `DB-PORT` , and `Server-port`. then,  As you mentioned DATABASE-URL as `Database dev name`, then we need `DB-Password`. Lastly `NODE-ENV`

2019-10-02 19:05 UTC, Crispy-lang commented
> Please, Christian! could you specify `DB-PORT` , and `Server-port`. then, As you mentioned DATABASE-URL as `Database dev name`, then we need `DB-Password`. Lastly `NODE-ENV`

i don't understand your question ?

2019-10-03 06:28 UTC, alexismajya approved these changes

2019-10-03 07:21 UTC, lemoissonM approved these changes

2019-10-03 07:31 UTC, urbanishimwe approved these changes

2019-10-03 08:40 UTC, merged