#168781804 email verification
andela/eagle-bn-backend pull request #22
Opened 2019-10-10 14:13 UTC by urbanishimwe

### What does this PR do?
- user can verify their email before they merge
#### Description of Task to be completed?
usually, users need to verify their email. to make sure that those emails belong to them
#### How should this be manually tested?
create an account on sendgrid, and generate your api key
#### Any background context you want to provide?
NAN
#### What are the relevant pivotal tracker stories?
[story](https://www.pivotaltracker.com/story/show/168781804)
#### Screenshots (if appropriate)
NAN
#### Questions:
NAN

2019-10-10 14:26 UTC, swaibat reviewed
your coverage is failing by a big percentage

2019-10-10 14:53 UTC, lemoissonM approved these changes

2019-10-10 14:54 UTC, alexismajya approved these changes

2019-10-10 15:10 UTC, swaibat approved these changes

2019-10-10 17:05 UTC, swaibat reviewed
test coverage is failing by a big percentage

2019-10-11 11:35 UTC, zellymiriam commented on src/controllers/userController.js
> +  async verifyEmail(req, res) {
Add a new line above this line

2019-10-11 11:39 UTC, zellymiriam commented on src/utils/stringHelper.js
> +  <a href ="https://eagle-bn-backend-staging.herokuapp.com/api/v1/users/verify/${token}"> verify email </a>`;
Make the host dynamic by picking the host from the request headers

2019-10-11 11:40 UTC, zellymiriam commented on src/routes/userRoutes.js
> +app.post('/verify', userController.requestEmailVerification);
we will not need this route

2019-10-11 11:53 UTC, nakiwuge requested changes
@urbanishimwe good job. There is some feedback I would like you to workon.

- Remove the token on signup from the response and just use it in the back to send the email for verification.
- Create a Gmail account for eagle and share the password and email with the team on the channel. 
- The user should only verify their account by accessing the token in the email
- The `/verify/:token` endpoint should be a `put` since you are modifying a field `isVerified` from the database

Also, I have left other comments on the PR kindly check them out.

2019-10-11 12:54 UTC, nakiwuge approved these changes

2019-10-11 12:57 UTC, merged