#169113440 edit or delete an accommodation facility
andela/eagle-bn-backend pull request #28
Opened 2019-10-16 02:02 UTC by alexismajya

#### What does this PR do?

- creates an `accommodation delete` endpoint 
- creates an`accommodation edit ` endpoint 
- creates a swagger documentation

#### Description of Task to be completed?

1) Have the following endpoints working:
- `api/v1/accommodations/editAccommodation/<id>`
- `api/v1/accommodations/deleteAccommodation/<id>`
2) Have a `swagger documentation` for those endpoints

#### How should this be manually tested?

After cloning this repository, run `npm run dev`. Then:
- Using `postman` test every endpoint above

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?

[Pivotal tracker story](https://www.pivotaltracker.com/story/show/169113440)

#### Screenshots (if appropriate)
N/A
#### Questions:

2019-10-17 11:57 UTC, swaibat reviewed
@alexismajya  great job but do mind first fixing hound and coveralls and codeclimate before reviews

2019-10-17 14:52 UTC, lemoissonM requested changes
please resolve the conflicts

2019-10-17 16:16 UTC, swaibat approved these changes

2019-10-17 16:22 UTC, urbanishimwe approved these changes

2019-10-17 16:50 UTC, lemoissonM approved these changes

2019-10-23 17:09 UTC, elchroy commented on src/middlewares/accommodationMiddleware.js
> +  },
This is not needed. We already have a middleware for this in `rolesMiddleware`

2019-10-23 17:09 UTC, elchroy commented on src/routes/accommodationRoute.js
> +  checkUserSupplier, isSupplierAccommodation, checkForImages, checkForImagesUpdate
Replare `checkUserSupplier ` with `checkHost` middleware from `rolesMiddleware`

2019-10-23 17:25 UTC, elchroy commented on src/tests/testAccomod.spec.js
> +        expect(res.body).to.have.property('status');
Assert that the fields are actually updated. `expect that address if 'kigali'`, etc. Also for name, and other test cases

2019-10-23 17:27 UTC, elchroy commented on src/tests/testAccomod.spec.js
> +        expect(res.body).to.have.property('status');
Check that there is no accommodation with `id` of 1, after making this delete request

2019-10-23 17:32 UTC, elchroy commented on src/validation/index.js
> +      new Check({ name: req }).str().min(5),
Include the name field validation to the `add-Accommodation`.

2019-10-24 10:12 UTC, merged