(chore: 168781798) Updated dotenv to ^8.1.0
andela/eagle-bn-backend pull request #7
Opened 2019-09-30 16:09 UTC by Crispy-lang

#### What does this PR do?
          Updated dotenv packages to ^8.1.0 from 6.0.0
#### How should this be manually tested?       

- import dotenv
- load all the environment variable using `dotenv.config()` from .env file
- call an environment variables using  `process.env.env_name`
#### What are the relevant pivotal tracker stories?
           #168781798

2019-09-30 16:32 UTC, urbanishimwe approved these changes

2019-10-01 07:32 UTC, lemoissonM requested changes
great job, however, you should watch the git naming conventions, and rename your PR title and put a body to your next commits

2019-10-01 08:06 UTC, nakiwuge requested changes
@Crispy-lang  good job however you have not fully completed your task. Kindly configure dotenv in the application. You just installed dot env

2019-10-01 13:59 UTC, urbanishimwe approved these changes

2019-10-01 14:14 UTC, swaibat approved these changes

2019-10-01 14:42 UTC, swaibat approved these changes

2019-10-01 14:43 UTC, urbanishimwe approved these changes

2019-10-02 15:29 UTC, closed without merging