#169700374 fix password validation
andela/eagle-bn-backend pull request #84
Opened 2019-11-12 10:24 UTC by lemoissonM

### What does this PR do?
Fix password validation
#### Description of Task to be completed?
- fix password validation 
- change message in test file
#### How should this be manually tested?
- npm run dev
- Signup with password : 12345678@@ or MMMMMM@@
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/169700374
#### Screenshots (if appropriate)
#### Questions:

2019-11-12 12:00 UTC, urbanishimwe requested changes

2019-11-12 12:00 UTC, urbanishimwe commented on src/utils/validator.js
> +      throw new Error(`${this.key} should contain letters, numbers and  at least 1 special character`);
Nice Work Here!
But, passwords like this `1       h j k *erm h` and `y1@ k j k l  0` will still work even tho it contains `whitespaces`
and passwords like `1234?$aqw` won't work! even tho `they should be allowed`
**Here is the suggestion:**
`(!this.val.match(/[a-z]+/) || !this.val.match(/[A-Z]+/) || !this.val.match(/[0-9]+/) || !this.val.match(/[-!$%^&*()_+|~=``{}\[\]:";'<>?,.\/]+/) || this.val.match(/\s+/))`
*explanation:*
`this.val.match(/\s+/)`: will check if there is any whitespace in the password.
`this.val.match(/[A-Z]+/)`: will check if the user provided any UPPER case chars(It is necessary)
`this.val.match(/[-!$%^&*()_+|~=``{}\[\]:";'<>?,.\/]+/)`: i just increased the species of valid `symbols`.

2019-11-13 07:02 UTC, urbanishimwe approved these changes

2019-11-13 13:48 UTC, alexismajya approved these changes

2019-11-13 13:55 UTC, merged